#!/usr/bin/env python3
"""Rebuild source-reproducible research CAD plus the primary fabrication kits."""
from __future__ import annotations
import subprocess
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
COMMANDS=[
 [sys.executable,"cad/generate_v2.py"],
 [sys.executable,"cad/generate_v3_experiments.py"],
 [sys.executable,"cad/generate_v3_photo_interp.py"],
 [sys.executable,"cad/generate_v3_video_refinements.py"],
 [sys.executable,"cad/generate_m2_v5_fabrication_kit.py"],
 [sys.executable,"cad/generate_m6_v2_fabrication_kit.py"],
 [sys.executable,"scripts/normalize_buildkit_step.py"],
 [sys.executable,"scripts/check_build_kits.py"],
]
for command in COMMANDS:
 print("+"," ".join(command)); subprocess.run(command,cwd=ROOT,check=True)
print("Research CAD and real-material M2/M6 fabrication kits rebuilt.")
print("Legacy all-solid reference CAD is preserved separately and is not regenerated by default.")
